name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Safer range that works with current Flutter stable
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # State / storage / utils
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI / charts / calendar / animations
  lottie: ^3.3.1
  badges: ^3.1.2
  table_calendar: ^3.0.9
  fl_chart: ^0.64.0

  # Media picker
  image_picker: ^1.1.0

  # Notifications / timezones
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # App info (version/build)
  package_info_plus: ^8.0.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/success_check.json
    - assets/animations/delete.json